---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: acmesh-dev

- name: test
  pull: never
  image: acmesh-dev
  command:
  - acme.sh
  - --version

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: acmesh-dev
    repo: spritsail/acme.sh
    tags:
    - latest
    - '%label io.spritsail.version.acme-sh | %auto'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

...
